version: "3.8"

services:
  frontend:
    image: hello-front-dev
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./todo-frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev -- --host

  backend:
    image: hello-back-dev
    container_name: backend
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/the_database
      - REDIS_URL=redis://redis:6379

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
