version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5173:5173
    working_dir: /usr/src/app
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    working_dir: /usr/src/app
    command: npm run dev

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend